### ISSUE TITLE
"Generic" Dynamic Converter and BitArray Converter

### ISSUE THREAD

**Issue by DNEAVES** [Billuc/glitr#2]
I'd like to request a converter to the `Dynamic` type.

I'm using glitr_convert and glitr_convert_cake for combined json and postgres type conversion. For most types/cases this is fine, and a type can be `glitr/convert/map`ped. For postgres table ID's I decided to use a UUID type, and conversion of this from cake/postgres is presenting an issue, where UUID's are being returned as a `BitArray`. I am able to work around the `cake/adaptor/postgres/run_{read/write}_query` decoder arg by using just the `gleam/dynamic` library and a specialized decoder function, although this means ignoring `glitr/convert/cake/cake_decode`.

I do see that a `BitArray` converter is under consideration, and I could absolutely use that if implemented by then `map`ping with `youid/uuid/{to/from}_bit_array`.

I also think a generic `Dynamic` converter could also be good, so any type already exporting `{to/from}_dynamic` or `decode/encode` functions, or custom types that can at least make their way to/from those, can easily be `map`ped using glitr.

**Comment by Billuc** [comment]
Hey, happy to hear you like the lib ! This is a nice suggestion, I will try working on it after eating 🙂

**Comment by Billuc** [comment]
BTW @DNEAVES I am currently moving stuff out of this repo including glitr_convert stuff. The new repo is simply convert (+ convert_json and others)
